### ISSUE TITLE
Support of query cell ID other than 10X format

### ISSUE THREAD

**Issue by Xieeeee** [satijalab/scChromHMM#2]
Hi,
I wonder whether grabbing query cells from the fragment.tsv file could be run the same as common_cells, ie providing a reference list for hashing or so. Why I am asking is because for other technique like Paired-Tag or Paired-seq the cell ID is like aa:bb:cc rather than XXX-1. It would be really great if versatile barcodes format would be considered, as this tool can be applied broader.

Thanks!!

**Comment by k3yavi** [comment]
I think that's a very good idea @Xieeeee and we are actively working on supporting such a feature. We'd let you know once we merge the support of the feature.
